[project]
site_name = "Calendar Documentation"
docs_dir = "docs"
site_dir = "docs/site"
repo_url = "https://github.com/Joshs-Dev-Quest/Calendar"
site_description = "Private selfhosted calendar"
edit_uri = '-/edit/main/docs/'

nav = [
  {"Home" = "index.md"},
  {"Contribution" = "CONTRIBUTION.md"},
  {"Architecture" = [
    {"Overview" = "architecture/overview.md"}
  ]},
  {"ADS" = [
    {"Overview" = "decisions/00-overview.md"},
    {"Template" = "decisions/00-template.md"},
    {"Decisions" = [
       {"01-Project" = "decisions/01-project.md"},
       {"02-Zensical" = "decisions/02-tool-zensical.md"}
    ]}
  ]}
]


[[project.theme.palette]]
scheme = "default"
palette.primary = "blue"
palette.accent = "cyan"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
palette.primary = "red"
palette.accent = "yellow"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"